url: http://www.Raybook.com

title: Raybook

keywords: 李泽彬

description: 李泽彬是在读顺德职业技术学院经管16电商四班一名学生现学习搜索引擎优化。

relative_permalinks: false

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []

exclude:
  - README.md
